version: "3.2"
services:
    elasticsearch:
        image: elasticsearch:7.6.2
        container_name: elasticsearch
        hostname: elasticsearch
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
            discovery.type: single-node
            # ELASTIC_PASSWORD: changeme
            # Use single node discovery in order to disable production mode and avoid bootstrap checks. see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
            # - "discovery.type=single-node"
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - elknetwork
    kibana:
        image: kibana:7.6.2
        container_name: kibana
        hostname: kibana
        ports:
            - 5601:5601
        links:
            - elasticsearch:elasticsearch
        depends_on:
          - elasticsearch
        networks:
          - elknetwork
    logstash:
        image: logstash:7.6.2
        container_name: logstash
        hostname: logstash
        command: --config.reload.automatic 
        ports:
            - "9101:5000/tcp"        
            - "9102:6000/tcp"        
            - 9600:9600
            - 8089:8089
        environment:
          LS_JAVA_OPTS: "-Xmx256m -Xms256m"
          # command: bash -c "bin/logstash-plugin install logstash-filter-json && logstash -f /etc/logstash/conf.d/logstash.conf "
        volumes:
          - type: bind
            source: ./logstash/config/logstash.yml
            target: /usr/share/logstash/config/logstash.yml
            read_only: true
          - type: bind
            source: ./logstash/config/pipelines.yml
            target: /usr/share/logstash/config/pipelines.yml
            read_only: true
          - type: bind
            source: ./logstash/pipeline
            target: /usr/share/logstash/pipeline
            read_only: true
          - type: bind
            source: ./logstash/data
            target: /var/lib/logstash/data
        links:
            - elasticsearch:elasticsearch
        depends_on:
          - elasticsearch
        networks:
          - elknetwork
networks:
    elknetwork:
        driver: bridge